### ISSUE TITLE
Just found this, wonderful tool. Congrats. I wonder....

### ISSUE THREAD

**Issue by Digimont** [rafaco/UnlimitedMultiBattles#2]
Doesn't matter, worked it out now....

**Comment by Digimont** [comment]
I read the Read Me (once I found it)

**Comment by rafaco** [comment]
Hi @Digimont, 

Sorry for the late answer and thank you for using my tool:

>a) if it is conceivable that this tool could be passed its running parameters, so it could jump straight into to the actual runs? It would only need to "Run X times", calculations etc will already have been performed, and it could be assumed the game is already in the right position.

I don't understand what you mean, but I'm happy that you worked it out. Please explain it better to me if you need any change or support in order to be able to integrate it with your Excel toolkit. It's your project published? Can you share it to me? If I find it interesting I would love to use it and to include a link to your project in my readme or even inside my tools to open yours directly passing some parameters.

>b) could an auto-sell option be included? That would be very valuable for everyone. I assume it would have to be a sell all or none, but I'm sure people would be happy with that.

This is not possible as this program only send periodic hotkeys to the game and there is not hotkeys available for opening an item to sell it. There is another project called [OmgClick](https://www.getomgclick.com/) that do what you want as it compare images and perform clicks. Keep in mind that while with my tool you only receive a warning about installing a program from an unknown source, this last one is recognized as a proper virus by Windows and you have to allow it under your own responsibility.

There are also other interesting projects for extracting the artifact and champions data from the PC game into an Excel, that you could find interesting if you don't know them already. Have a look to [this](https://github.com/LukeCroteau/RaidExtractor) or [this](https://www.reddit.com/r/RaidShadowLegends/comments/kukw3c/raid_extractor_continues_to_develop_free/).

Cheers!

**Comment by Digimont** [comment]
Hi Rafael, sorry also for my late reply, but my mail sorter sent your message to spam...

 

I had worked out the answers to all my questions.. at first I didn't realise you were using in-game keys, then saw the limitations imposed either unwittingly or deliberately by Plarium (eg while you can select A1/A2/A3, you can't a) target an enemy/ally or b) execute the move). So, my solution must still regrettably involve mouse control. I'll be writing my own in VBA. Auto-sell is complicated using mouse because the box you need to click moves depending on what events/tournaments are running. I'm probably going to have to click in 2 or 3 places...inelegant, but as long as it gets the job done.

 

The toolkit is still under development and not ready for publishing yet. I could publish as is, but then my schedule ceases to be my own, as I'll have to go into "maintenance mode" which delays more new stuff. I'd say its about 2/3rds complete. I still have some fairly major pieces to build (Clan Boss and Arena calculators). While I realise these things already exist and I can't better Deadwood Jedi's Clan Boss calculator, I still want to do them, because it helps me to understand the game better. 

 

Yes, I'm in regular contact with Luke and already use Raid Extractor to import data. I'm also a beta tester for HellHades Raid Optimiser and won't be doing anything along those lines. 

 

Regards

David
